database: # MariaDB only
  username: user
  host: localhost
  port: 3306
  password: password
  database: CraftUtils
commands:
  tp: true
  message: true
  tpAsk: true
  enderChest: true
  adminGUI: true
  alias: true
  ability: true
  homes: true
  warps: true