# Configuration for player messages
msg:
  # Valid content placeholders are %actor%, %recipient% and %message%.
  #  Valid formatting placeholders are found in net.kyori.adventure.text.format.NamedTextColor, but use Lowercase
  messages:
    send-message: "%yellow%%actor% %gray%to %aqua%%recipient%: %italic%%gray%%message%"
    receive-message: "%yellow%%actor% sent you: %italic%%gray%%message%"
    no-target: "%red%You don't have anyone to reply to."
    offline-target: "%red%The player you are replying to is offline."

# Developer settings for debugging and advanced plugin configuration
developer-settings:
  # Enables debug logging for the plugin
  enable-logging: false