name: CraftUtils
version: 1.0.2
main: dev.craftefix.craftUtils.Main
api-version: 1.21.8
data-folder: CraftUtils
description: A simple Utils plugin for Paper
website: craftefix.dev
authors:
  - Craftefix
folia-supported: true

permissions:
  CraftUtils.mute:
    description: Allows muting players
    default: op
  CraftUtils.mute.notify:
    description: Receive notifications when players are muted
    default: op
  CraftUtils.unmute:
    description: Allows unmuting players
    default: op
  CraftUtils.pardon:
    description: Allows pardoning (unbanning) players
    default: op
  CraftUtils.pardon.notify:
    description: Receive notifications when players are pardoned
    default: op