name: CraftUtils
version: 1.0.0
main: dev.craftefix.craftUtils.Main
api-version: 1.21.8
description: A simple Utils plugin for Paper
website: craftefix.dev
authors:
  - Craftefix
folia-supported: true