name: Build & Release Alpha

on:
  push:
    branches:
      - alpha-releases
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0  # Required for proper commit history

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '23'

      - name: Install GitHub CLI
        run: |
          gh --version

      - name: Build with Gradle
        run: |
            ./gradlew --build-cache --parallel shadowJar \
              -Dorg.gradle.java.home="$JAVA_HOME_23_X64" \
              -Djava.home="$JAVA_HOME_23_X64"
            ls -lh build/libs/
            echo $JAVA_HOME_23_X64
            echo $JAVA_HOME
        

      - name: Version Bump and Release
        id: versioning
        run: |
          set -x
          echo "🔍 Starting version bump process..."
          
          VERSION_FILE="build.gradle"
          PLUGIN_FILE="src/main/resources/paper-plugin.yml"
          
          echo "📄 Parsing version from $VERSION_FILE"
          CURRENT_VERSION=$(grep "version\s*=" "$VERSION_FILE" | awk -F"['\"]" '{print $2}')
          [ -z "$CURRENT_VERSION" ] && { echo "❌ Could not find version in $VERSION_FILE"; exit 1; }
          echo "ℹ️ Current version: $CURRENT_VERSION"

          # Calculate new version (your existing logic)
          if [[ "$CURRENT_VERSION" =~ \.b[0-9]+$ ]]; then
            BASE_VERSION="${CURRENT_VERSION%.b*}"
            BUILD_NUMBER="${CURRENT_VERSION##*.b}"
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            NEW_VERSION="${BASE_VERSION}.b${NEW_BUILD_NUMBER}"
          else
            NEW_VERSION="${CURRENT_VERSION}.b1"
          fi
          echo "🆕 New version: $NEW_VERSION"

          # Update build.gradle
          sed -i.bak "s/version\s*=.*/version = '${NEW_VERSION}'/" "$VERSION_FILE"
          rm -f "${VERSION_FILE}.bak"

          # Update ONLY the root 'version:' in paper-plugin.yml
          sed -i.bak -E "s/^(version:[[:space:]]*).*/\1${NEW_VERSION}/" "$PLUGIN_FILE"
          rm -f "${PLUGIN_FILE}.bak"

          
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: essentials
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 3
