name: Alpha Builder

on:
  push:
    branches:
      - alpha-releases
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v4.2.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Up Java
        uses: actions/setup-java@v4.7.0
        with:
            distribution: 'corretto'
            java-version: '23'

      - name: Build with Gradle
        run: |
            ./gradlew --parallel --configure-on-demand \
              -Dorg.gradle.java.home="$JAVA_HOME" \
              -Dorg.gradle.jvmargs="-Xmx6g -XX:MaxMetaspaceSize=1g" \
              -Dorg.gradle.caching=false \
              -x test \
                shadowJar

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create Release
        id: release
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          JAR_PATH=$(ls build/libs/*-all.jar)
          JAR_NAME="CraftUtils-${COMMIT_HASH}.jar"
          mv -v "$JAR_PATH" "build/libs/${JAR_NAME}"
          gh release create "${COMMIT_HASH}" "build/libs/${JAR_NAME}" \
            --title "Alpha Build ${COMMIT_HASH}" \
            --notes "Automated pre/alpha release from commit ${COMMIT_HASH}" \
            --repo "${GITHUB_REPOSITORY}" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version_bump:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Version Bump
        id: versioning
        run: |
          set -x
          VERSION_FILE="build.gradle"
          PLUGIN_FILE="src/main/resources/paper-plugin.yml"
          CURRENT_VERSION=$(grep "version\s*=" "$VERSION_FILE" | awk -F"['\"]" '{print $2}')
          [ -z "$CURRENT_VERSION" ] && { echo "Could not find version in $VERSION_FILE"; exit 1; }
          if [[ "$CURRENT_VERSION" =~ \.b[0-9]+$ ]]; then
            BASE_VERSION="${CURRENT_VERSION%.b*}"
            BUILD_NUMBER="${CURRENT_VERSION##*.b}"
            NEW_BUILD_NUMBER=$((BUILD_NUMBER +1))
            NEW_VERSION="${BASE_VERSION}.b${NEW_BUILD_NUMBER}"
          else
            NEW_VERSION="${CURRENT_VERSION}.b1"
          fi
          sed -i.bak "s/version\s*=.*/version = '${NEW_VERSION}'/" "$VERSION_FILE"
          rm -f "${VERSION_FILE}.bak"
          sed -i.bak -E "s/^(version:[[:space:]]*).*/\1${NEW_VERSION}/" "$PLUGIN_FILE"
          rm -f "${PLUGIN_FILE}.bak"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add "$VERSION_FILE" "$PLUGIN_FILE"
          git commit -m "Bump version to ${NEW_VERSION}" --quiet
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:alpha-releases --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}